### ISSUE TITLE
Panel stays revealed after unlocking screen or restarting shell

### ISSUE THREAD

**Issue by RedBearAK** [tuxor1337/hidetopbar#365]
I really enjoy this extension. It replicates the ability to hide the menu bar that was finally introduced in macOS El Capitan a few years ago. It's nice to have a bit more vertical screen space but still have quick access to the top panel without invoking the whole overview. 

There is a minor issue that I hope someone will be able to solve one day. I use the "autohide" option, which is supposed to keep the panel hidden unless I bump the top edge of the screen with the mouse cursor. But from time to time in certain circumstances the panel will make itself visible and remain visible until I slide over the panel area with the mouse cursor and then go back off. Most frequently this is when restarting the GNOME shell for any reason, or when unlocking the display from the lock screen. 

I've seen this sort of behavior also when trying to autohide a panel in Xfce, it would often fail to hide the panel even though the mouse was not on top of the panel area, until sliding the mouse cursor on and off the panel. I know Xfce is also based on GTK, so perhaps this is just something GTK in general is not very good at. But it would be nice if the panel could do a better job hiding itself whenever the mouse cursor is not actively on top of, or at least near, the displayed panel area. Instead what the panel seems to do is sit and stubbornly wait for a specific "mouse cursor leaving panel area" event before it will hide itself. As if without that specific event it has no way of knowing that the mouse cursor is not on the panel or even anywhere near the top edge of the screen. 

Should probably note that I've observed this issue with the extension through multiple versions of Ubuntu from 20.04 to 22.04, and also in Fedora 34 to 36.

**Comment by tuxor1337** [comment]
Possibly related: #154 #182 #183 #202 #265 #354 #365

Unfortunately, since there seems to be no way to reproduce this issue at will, there's not much we can do to fix it.

**Comment by ddnexus** [comment]
@tuxor1337 One simple way to reproduce the issue is opening a menu of the panel and picking an item or clicking outside the menu to close the menu.

If the menu closes and the pointer is out of the panel, I would like to have a second or so of delay (that allow you to just come back to the panel), and after that - if the pointer is out of the panel - it should close automatically.

Instead, it looks like HTP is not aware of the condition (that should have been triggered by to top bar menu out) and waits until it is triggered again.

Maybe we need some polling system (while the panel is visible) to check every second or so, whether there is some menu out or not.

**Comment by tuxor1337** [comment]
@ddnexus Thanks, that's really quite helpful! I'm wondering whether #356 is able to fix this? Unfortunately, I don't have time to test this in the next few days, so any feedback is very welcome. :)

**Comment by ddnexus** [comment]
Yes! It looks like #356 fixes it perfectly in 42.2! Thank you!

**Comment by tuxor1337** [comment]
Closing as fixed by #356

**Comment by RedBearAK** [comment]
@tuxor1337 

This issue isn't fixed for me. It's been a while so I assume as long as my extension is up to date this should be part of it. But my panel still stays revealed after unlocking the screen, until I move the mouse over the panel and off. 

Ubuntu 22.04, GNOME 42.2

**Comment by ddnexus** [comment]
Sorry, when I stated that it was perfectly fixed, I was focused on the fact that it fixed the worse problem of disappearing during the normal usage (e.g. closing a menu without selecting an item) and I totally forgot the title of this issue.

Personally the unlocking problem doesn't bother me at all, I almost consider it as a feature, because I have the habit to look at the clock after an unlock, however, the original issue is still there.

**Comment by tuxor1337** [comment]
While I still can't reproduce this on my system, some people still seem to see this behavior (see also #387). So I'm reopening this...

**Comment by RedBearAK** [comment]
> While I still can't reproduce this on my system, some people still seem to see this behavior (see also #387). So I'm reopening this...

That actually sounds like kind of the opposite situation. Which I’ve had happen a few times lately too, requiring me to use the “Alt-F2,r” trick to restart the shell in order to get the top bar back.

**Comment by tuxor1337** [comment]
Ah yes, you are right. I should pay more attention :smile:
